import { IssueRecord } from '../types';

export const INITIAL_SAMPLE_ISSUES: IssueRecord[] = [
  // Genesis Application (Demonstrating project splitting into Genesis IOS and Genesis AOS)
  {
    id: 'GEN-101',
    project: 'Genesis',
    baseProject: 'Genesis',
    summary: '[IOS] Keychain token migration failure on iOS 18',
    created: '2026-08-02',
    createdRaw: '2026-08-02 10:00',
    statusCategoryChange: '2026-08-06',
    statusCategoryChangeRaw: '2026-08-06 14:00',
    status: 'Done',
    issueType: 'Bug',
    priority: 'High',
    assignee: 'Sarah Chen',
    platformTag: 'IOS',
    raw: {}
  },
  {
    id: 'GEN-102',
    project: 'Genesis',
    baseProject: 'Genesis',
    summary: '[AOS] Push notification token refresh crashes in background',
    created: '2026-08-04',
    createdRaw: '2026-08-04 11:30',
    statusCategoryChange: '2026-08-09',
    statusCategoryChangeRaw: '2026-08-09 16:20',
    status: 'Done',
    issueType: 'Bug',
    priority: 'Critical',
    assignee: 'Alex Rivera',
    platformTag: 'AOS',
    raw: {}
  },
  {
    id: 'GEN-103',
    project: 'Genesis',
    baseProject: 'Genesis',
    summary: '[IOS] CoreData SQLite schema migration lockup',
    created: '2026-08-11',
    createdRaw: '2026-08-11 15:45',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'In Progress',
    issueType: 'Bug',
    priority: 'High',
    assignee: 'Sarah Chen',
    platformTag: 'IOS',
    securityDueDate: '2026-08-16',
    securityDueDateRaw: '2026-08-16',
    raw: {}
  },
  {
    id: 'GEN-104',
    project: 'Genesis',
    baseProject: 'Genesis',
    summary: '[AOS] Jetpack Compose navigation gesture conflict on Android 15',
    created: '2026-08-13',
    createdRaw: '2026-08-13 13:10',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'Open',
    issueType: 'Bug',
    priority: 'Medium',
    assignee: 'Alex Rivera',
    platformTag: 'AOS',
    securityDueDate: '2026-08-22',
    securityDueDateRaw: '2026-08-22',
    raw: {}
  },
  {
    id: 'GEN-105',
    project: 'Genesis',
    baseProject: 'Genesis',
    summary: 'Cloud sync WebSocket heartbeat disconnects during deep sleep',
    created: '2026-08-05',
    createdRaw: '2026-08-05 09:00',
    statusCategoryChange: '2026-08-08',
    statusCategoryChangeRaw: '2026-08-08 11:00',
    status: 'Done',
    issueType: 'Bug',
    priority: 'High',
    assignee: 'David Kim',
    platformTag: 'GENERAL',
    raw: {}
  },
  {
    id: 'GEN-106',
    project: 'Genesis',
    baseProject: 'Genesis',
    summary: 'API gateway rate limiting returns 429 on bulk profile fetch',
    created: '2026-08-10',
    createdRaw: '2026-08-10 14:15',
    statusCategoryChange: '2026-08-14',
    statusCategoryChangeRaw: '2026-08-14 16:30',
    status: 'Done',
    issueType: 'Task',
    priority: 'Medium',
    assignee: 'David Kim',
    platformTag: 'GENERAL',
    raw: {}
  },
  {
    id: 'GEN-107',
    project: 'Genesis',
    baseProject: 'Genesis',
    summary: 'User profile avatar CDN cache invalidation delay',
    created: '2026-08-12',
    createdRaw: '2026-08-12 16:20',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'In Progress',
    issueType: 'Improvement',
    priority: 'Low',
    assignee: 'David Kim',
    platformTag: 'GENERAL',
    raw: {}
  },

  // Mobile Banking App
  {
    id: 'BANK-101',
    project: 'Mobile Banking App',
    summary: '[IOS] Face ID authentication fails after system lock',
    created: '2026-08-01',
    createdRaw: '2026-08-01 09:15',
    statusCategoryChange: '2026-08-05',
    statusCategoryChangeRaw: '2026-08-05 14:20',
    status: 'Done',
    issueType: 'Bug',
    priority: 'High',
    assignee: 'Sarah Chen',
    platformTag: 'IOS',
    raw: {}
  },
  {
    id: 'BANK-102',
    project: 'Mobile Banking App',
    summary: '[AOS] Biometric prompt crashes on Samsung One UI 6',
    created: '2026-08-03',
    createdRaw: '2026-08-03 11:30',
    statusCategoryChange: '2026-08-08',
    statusCategoryChangeRaw: '2026-08-08 17:00',
    status: 'Done',
    issueType: 'Bug',
    priority: 'Critical',
    assignee: 'Alex Rivera',
    platformTag: 'AOS',
    raw: {}
  },
  {
    id: 'BANK-103',
    project: 'Mobile Banking App',
    summary: '[IOS] Apple Pay tokenization timeout on iOS 18.2',
    created: '2026-08-10',
    createdRaw: '2026-08-10 14:00',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'In Progress',
    issueType: 'Bug',
    priority: 'High',
    assignee: 'Sarah Chen',
    platformTag: 'IOS',
    securityDueDate: '2026-08-17',
    securityDueDateRaw: '2026-08-17',
    raw: {}
  },
  {
    id: 'BANK-104',
    project: 'Mobile Banking App',
    summary: '[AOS] Push notifications delay on Xiaomi devices (battery saver)',
    created: '2026-08-12',
    createdRaw: '2026-08-12 16:45',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'Open',
    issueType: 'Bug',
    priority: 'Medium',
    assignee: 'Alex Rivera',
    platformTag: 'AOS',
    securityDueDate: '2026-08-25',
    securityDueDateRaw: '2026-08-25',
    raw: {}
  },
  {
    id: 'BANK-105',
    project: 'Mobile Banking App',
    summary: 'Backend API returning 500 on international wire transfers',
    created: '2026-08-02',
    createdRaw: '2026-08-02 08:30',
    statusCategoryChange: '2026-08-04',
    statusCategoryChangeRaw: '2026-08-04 12:00',
    status: 'Done',
    issueType: 'Defect',
    priority: 'Critical',
    assignee: 'David Kim',
    platformTag: 'GENERAL',
    raw: {}
  },
  {
    id: 'BANK-106',
    project: 'Mobile Banking App',
    summary: 'Statement PDF generator truncates long currency symbols',
    created: '2026-08-09',
    createdRaw: '2026-08-09 10:20',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'Under Review',
    issueType: 'Bug',
    priority: 'Low',
    assignee: 'David Kim',
    platformTag: 'GENERAL',
    raw: {}
  },
  {
    id: 'BANK-107',
    project: 'Mobile Banking App',
    summary: 'Legacy SMS 2FA gateway retirement cleanup',
    created: '2026-07-20',
    createdRaw: '2026-07-20 15:00',
    statusCategoryChange: '2026-08-02',
    statusCategoryChangeRaw: '2026-08-02 11:15',
    status: 'Cancelled',
    issueType: 'Task',
    priority: 'Low',
    assignee: 'Emma Watson',
    platformTag: 'GENERAL',
    raw: {}
  },

  // E-Commerce Checkout Platform
  {
    id: 'ECOM-201',
    project: 'E-Commerce Checkout Platform',
    summary: '[IOS] Safari popup blocker prevents 3D Secure redirect',
    created: '2026-08-04',
    createdRaw: '2026-08-04 13:10',
    statusCategoryChange: '2026-08-07',
    statusCategoryChangeRaw: '2026-08-07 16:30',
    status: 'Done',
    issueType: 'Bug',
    priority: 'High',
    assignee: 'Elena Rostova',
    platformTag: 'IOS',
    raw: {}
  },
  {
    id: 'ECOM-202',
    project: 'E-Commerce Checkout Platform',
    summary: '[AOS] Chrome autofill covers credit card CVV input',
    created: '2026-08-06',
    createdRaw: '2026-08-06 15:20',
    statusCategoryChange: '2026-08-11',
    statusCategoryChangeRaw: '2026-08-11 09:45',
    status: 'Done',
    issueType: 'Bug',
    priority: 'Medium',
    assignee: 'Marcus Vance',
    platformTag: 'AOS',
    raw: {}
  },
  {
    id: 'ECOM-203',
    project: 'E-Commerce Checkout Platform',
    summary: '[IOS] Coupon code field paste gesture triggers keyboard jump',
    created: '2026-08-14',
    createdRaw: '2026-08-14 11:00',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'In Progress',
    issueType: 'Bug',
    priority: 'Medium',
    assignee: 'Elena Rostova',
    platformTag: 'IOS',
    raw: {}
  },
  {
    id: 'ECOM-204',
    project: 'E-Commerce Checkout Platform',
    summary: '[AOS] Back navigation from confirmation page creates duplicate charge',
    created: '2026-08-15',
    createdRaw: '2026-08-15 18:30',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'Open',
    issueType: 'Bug',
    priority: 'Critical',
    assignee: 'Marcus Vance',
    platformTag: 'AOS',
    raw: {}
  },
  {
    id: 'ECOM-205',
    project: 'E-Commerce Checkout Platform',
    summary: 'Tax calculation rounding error for multi-item promotional bundles',
    created: '2026-08-05',
    createdRaw: '2026-08-05 09:00',
    statusCategoryChange: '2026-08-09',
    statusCategoryChangeRaw: '2026-08-09 14:15',
    status: 'Done',
    issueType: 'Bug',
    priority: 'High',
    assignee: 'Jordan Lee',
    platformTag: 'GENERAL',
    raw: {}
  },
  {
    id: 'ECOM-206',
    project: 'E-Commerce Checkout Platform',
    summary: 'Abandoned cart webhook sends email with expired session link',
    created: '2026-08-13',
    createdRaw: '2026-08-13 10:45',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'To Do',
    issueType: 'Bug',
    priority: 'Medium',
    assignee: 'Jordan Lee',
    platformTag: 'GENERAL',
    raw: {}
  },

  // Logistics & Rider Dispatch
  {
    id: 'LOG-301',
    project: 'Logistics & Rider Dispatch',
    summary: '[AOS] Background GPS tracking throttled in doze mode',
    created: '2026-08-02',
    createdRaw: '2026-08-02 07:45',
    statusCategoryChange: '2026-08-06',
    statusCategoryChangeRaw: '2026-08-06 18:20',
    status: 'Done',
    issueType: 'Bug',
    priority: 'Critical',
    assignee: 'Vikram Patel',
    platformTag: 'AOS',
    raw: {}
  },
  {
    id: 'LOG-302',
    project: 'Logistics & Rider Dispatch',
    summary: '[IOS] Turn-by-turn audio muting CarPlay navigation stream',
    created: '2026-08-07',
    createdRaw: '2026-08-07 14:30',
    statusCategoryChange: '2026-08-12',
    statusCategoryChangeRaw: '2026-08-12 11:00',
    status: 'Done',
    issueType: 'Bug',
    priority: 'High',
    assignee: 'Claire Becker',
    platformTag: 'IOS',
    raw: {}
  },
  {
    id: 'LOG-303',
    project: 'Logistics & Rider Dispatch',
    summary: '[IOS] Live Activity dynamic island widget stops updating after 15 min',
    created: '2026-08-11',
    createdRaw: '2026-08-11 16:10',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'In Progress',
    issueType: 'Bug',
    priority: 'High',
    assignee: 'Claire Becker',
    platformTag: 'IOS',
    raw: {}
  },
  {
    id: 'LOG-304',
    project: 'Logistics & Rider Dispatch',
    summary: '[AOS] Camera barcode scanner fails to focus in low light conditions',
    created: '2026-08-13',
    createdRaw: '2026-08-13 12:00',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'Open',
    issueType: 'Bug',
    priority: 'Medium',
    assignee: 'Vikram Patel',
    platformTag: 'AOS',
    raw: {}
  },
  {
    id: 'LOG-305',
    project: 'Logistics & Rider Dispatch',
    summary: 'Dispatcher map cluster rendering freezes with >500 active couriers',
    created: '2026-08-08',
    createdRaw: '2026-08-08 10:15',
    statusCategoryChange: '2026-08-14',
    statusCategoryChangeRaw: '2026-08-14 16:40',
    status: 'Done',
    issueType: 'Performance',
    priority: 'High',
    assignee: 'Samira Roy',
    platformTag: 'GENERAL',
    raw: {}
  },
  {
    id: 'LOG-306',
    project: 'Logistics & Rider Dispatch',
    summary: 'Geofence trigger false positive on delivery arrival radius',
    created: '2026-08-16',
    createdRaw: '2026-08-16 09:30',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'Investigating',
    issueType: 'Bug',
    priority: 'High',
    assignee: 'Samira Roy',
    platformTag: 'GENERAL',
    raw: {}
  },

  // Merchant Portal & Analytics
  {
    id: 'MERCH-401',
    project: 'Merchant Portal & Analytics',
    summary: 'CSV export timeout for merchants with over 50,000 monthly orders',
    created: '2026-08-03',
    createdRaw: '2026-08-03 14:00',
    statusCategoryChange: '2026-08-06',
    statusCategoryChangeRaw: '2026-08-06 17:15',
    status: 'Done',
    issueType: 'Bug',
    priority: 'High',
    assignee: 'Liam O\'Connor',
    platformTag: 'GENERAL',
    raw: {}
  },
  {
    id: 'MERCH-402',
    project: 'Merchant Portal & Analytics',
    summary: 'Settlement payout breakdown missing surcharge fees column',
    created: '2026-08-09',
    createdRaw: '2026-08-09 11:45',
    statusCategoryChange: '2026-08-13',
    statusCategoryChangeRaw: '2026-08-13 15:30',
    status: 'Done',
    issueType: 'Bug',
    priority: 'Medium',
    assignee: 'Liam O\'Connor',
    platformTag: 'GENERAL',
    raw: {}
  },
  {
    id: 'MERCH-403',
    project: 'Merchant Portal & Analytics',
    summary: '[IOS] iPad split-view renders revenue graph overflow',
    created: '2026-08-12',
    createdRaw: '2026-08-12 13:20',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'In Progress',
    issueType: 'Bug',
    priority: 'Medium',
    assignee: 'Zoe Martinez',
    platformTag: 'IOS',
    raw: {}
  },
  {
    id: 'MERCH-404',
    project: 'Merchant Portal & Analytics',
    summary: 'Role permission editor allows store managers to revoke owner credentials',
    created: '2026-08-14',
    createdRaw: '2026-08-14 08:50',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'Open',
    issueType: 'Security',
    priority: 'Critical',
    assignee: 'Zoe Martinez',
    platformTag: 'GENERAL',
    raw: {}
  },
  {
    id: 'MERCH-405',
    project: 'Merchant Portal & Analytics',
    summary: 'Discontinued test merchant webhook testing tool endpoint',
    created: '2026-07-28',
    createdRaw: '2026-07-28 10:00',
    statusCategoryChange: '2026-08-01',
    statusCategoryChangeRaw: '2026-08-01 14:00',
    status: 'Canceled',
    issueType: 'Task',
    priority: 'Low',
    assignee: 'Liam O\'Connor',
    platformTag: 'GENERAL',
    raw: {}
  },

  // InfoSec / Application Security Audit Tickets (Bracketed Subprojects & Platform Tags)
  {
    id: 'SEC-201',
    project: 'InfoSec',
    baseProject: 'InfoSec',
    summary: '[Infosec][AOS][Staffcentral][Github-Codereview] Exposed Appstore Credentials',
    created: '2026-08-03',
    createdRaw: '2026-08-03 10:15',
    statusCategoryChange: '2026-08-07',
    statusCategoryChangeRaw: '2026-08-07 16:30',
    status: 'Done',
    issueType: 'Vulnerability',
    priority: 'Critical',
    assignee: 'Alex Rivera',
    platformTag: 'AOS',
    raw: {}
  },
  {
    id: 'SEC-202',
    project: 'InfoSec',
    baseProject: 'InfoSec',
    summary: '[Infosec][AOS][Staffcentral] Exposed Quekod API Credential',
    created: '2026-08-04',
    createdRaw: '2026-08-04 11:20',
    statusCategoryChange: '2026-08-09',
    statusCategoryChangeRaw: '2026-08-09 14:00',
    status: 'Done',
    issueType: 'Vulnerability',
    priority: 'High',
    assignee: 'Alex Rivera',
    platformTag: 'AOS',
    raw: {}
  },
  {
    id: 'SEC-203',
    project: 'InfoSec',
    baseProject: 'InfoSec',
    summary: '[InfoSec][AOS][Staffcentral] Unauthorize user can view other users badge',
    created: '2026-08-08',
    createdRaw: '2026-08-08 14:45',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'In Progress',
    issueType: 'Vulnerability',
    priority: 'High',
    assignee: 'Alex Rivera',
    platformTag: 'AOS',
    securityDueDate: '2026-08-15',
    securityDueDateRaw: '2026-08-15',
    raw: {}
  },
  {
    id: 'SEC-204',
    project: 'InfoSec',
    baseProject: 'InfoSec',
    summary: '[InfoSec] [AOS] [Doorspace] Exposed API Keys for Doorspace AOS',
    created: '2026-08-06',
    createdRaw: '2026-08-06 09:30',
    statusCategoryChange: '2026-08-11',
    statusCategoryChangeRaw: '2026-08-11 15:10',
    status: 'Done',
    issueType: 'Vulnerability',
    priority: 'Critical',
    assignee: 'Sarah Chen',
    platformTag: 'AOS',
    securityDueDate: '2026-08-10',
    securityDueDateRaw: '2026-08-10',
    raw: {}
  },
  {
    id: 'SEC-205',
    project: 'InfoSec',
    baseProject: 'InfoSec',
    summary: '[InfoSec] [AOS] [Doorspace] A user can expose sensitive username and password credential',
    created: '2026-08-10',
    createdRaw: '2026-08-10 13:00',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'Open',
    issueType: 'Vulnerability',
    priority: 'High',
    assignee: 'Sarah Chen',
    platformTag: 'AOS',
    securityDueDate: '2026-08-17',
    securityDueDateRaw: '2026-08-17',
    raw: {}
  },
  {
    id: 'SEC-206',
    project: 'InfoSec',
    baseProject: 'InfoSec',
    summary: '[InfoSec][AOS][Staffcentral] Exposed integration username and password',
    created: '2026-08-07',
    createdRaw: '2026-08-07 16:15',
    statusCategoryChange: '2026-08-12',
    statusCategoryChangeRaw: '2026-08-12 17:00',
    status: 'Done',
    issueType: 'Vulnerability',
    priority: 'Critical',
    assignee: 'Alex Rivera',
    platformTag: 'AOS',
    securityDueDate: '2026-08-12',
    securityDueDateRaw: '2026-08-12',
    raw: {}
  },
  {
    id: 'SEC-207',
    project: 'InfoSec',
    baseProject: 'InfoSec',
    summary: '[InfoSec][AOS][Radio] Exposed Credentials',
    created: '2026-08-05',
    createdRaw: '2026-08-05 15:40',
    statusCategoryChange: '2026-08-10',
    statusCategoryChangeRaw: '2026-08-10 11:20',
    status: 'Done',
    issueType: 'Vulnerability',
    priority: 'High',
    assignee: 'David Kim',
    platformTag: 'AOS',
    securityDueDate: '2026-08-09',
    securityDueDateRaw: '2026-08-09',
    raw: {}
  },
  {
    id: 'SEC-208',
    project: 'InfoSec',
    baseProject: 'InfoSec',
    summary: '[InfoSec][AOS][Tap] Exposed API Key',
    created: '2026-08-09',
    createdRaw: '2026-08-09 10:10',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'In Progress',
    issueType: 'Vulnerability',
    priority: 'High',
    assignee: 'David Kim',
    platformTag: 'AOS',
    securityDueDate: '2026-08-14',
    securityDueDateRaw: '2026-08-14',
    raw: {}
  },
  {
    id: 'SEC-209',
    project: 'InfoSec',
    baseProject: 'InfoSec',
    summary: '[InfoSec] [AOS] [Doorspace] Sensitive data exposure',
    created: '2026-08-11',
    createdRaw: '2026-08-11 12:30',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'Open',
    issueType: 'Vulnerability',
    priority: 'Medium',
    assignee: 'Sarah Chen',
    platformTag: 'AOS',
    securityDueDate: '2026-08-24',
    securityDueDateRaw: '2026-08-24',
    raw: {}
  },
  {
    id: 'SEC-210',
    project: 'InfoSec',
    baseProject: 'InfoSec',
    summary: '[InfoSec] [AOS] [Boardroom] Code activation is vulnerable to bruteforce.',
    created: '2026-08-12',
    createdRaw: '2026-08-12 14:00',
    statusCategoryChange: '',
    statusCategoryChangeRaw: '',
    status: 'Open',
    issueType: 'Vulnerability',
    priority: 'High',
    assignee: 'Alex Rivera',
    platformTag: 'AOS',
    securityDueDate: '2026-08-16',
    securityDueDateRaw: '2026-08-16',
    raw: {}
  },
  {
    id: 'SEC-211',
    project: 'InfoSec',
    baseProject: 'InfoSec',
    summary: '[InfoSec][IOS][Staffcentral] Keychain access group entitlement misconfiguration',
    created: '2026-08-02',
    createdRaw: '2026-08-02 09:00',
    statusCategoryChange: '2026-08-06',
    statusCategoryChangeRaw: '2026-08-06 15:30',
    status: 'Done',
    issueType: 'Vulnerability',
    priority: 'Critical',
    assignee: 'Sarah Chen',
    platformTag: 'IOS',
    raw: {}
  },
  {
    id: 'SEC-212',
    project: 'InfoSec',
    baseProject: 'InfoSec',
    summary: '[InfoSec][Staffcentral] Admin endpoint CORS wildcards allow unauthorized origin access',
    created: '2026-08-05',
    createdRaw: '2026-08-05 11:00',
    statusCategoryChange: '2026-08-08',
    statusCategoryChangeRaw: '2026-08-08 16:45',
    status: 'Done',
    issueType: 'Vulnerability',
    priority: 'High',
    assignee: 'David Kim',
    platformTag: 'GENERAL',
    raw: {}
  }
];
